services:
  web:
    build:
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: dev
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./mini-ecommerce/dist:/usr/share/nginx/html
      - ./backend/public/images:/images
    depends_on:
      - web

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Interface Web
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  matomo_db:
    image: mariadb:10.5
    command: --max-allowed-packet=64MB
    environment:
      MYSQL_ROOT_PASSWORD: matomo_root_password
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo_user
      MYSQL_PASSWORD: matomo_password
    volumes:
      - matomo_db_data:/var/lib/mysql
    restart: always

  matomo:
    image: matomo:latest
    ports:
      - "8082:80"
    environment:
      MATOMO_DATABASE_HOST: matomo_db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo_user
      MATOMO_DATABASE_PASSWORD: matomo_password
      MATOMO_DATABASE_DBNAME: matomo
    volumes:
      - matomo_data:/var/www/html
    depends_on:
      - matomo_db
    restart: always



volumes:
  db_data:
  matomo_data:
  matomo_db_data:
