version: '3.8'

services:
  web:
    build:
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/var/www/html
    expose:
      - "80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./mini-ecommerce/dist:/usr/share/nginx/html
    depends_on:
      - web

volumes:
  db_data:
