nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*'] # URL frontend prod
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/': ~
