nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']  # Autoriser tous les en-têtes
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/': ~